server:
  port: 8091
spring:
  rabbitmq:
    host: 172.22.162.132
    port: 5672
    username: guest
    password: guest
  application:
    name: contoller
  cloud:
    stream:
      bindings:
        input:
          destination: myMessgae
        output:
          destination: myMessgae
env:
  dev
user:
  name: lili
  age: 11
